### ISSUE TITLE
这个apk没法安装，提示与同名文件包冲突

### ISSUE THREAD

**Issue by honghongtu** [xiaotuan/ImeiAndMeidSettings#2]
这个apk没法安装，提示与同名文件包冲突

**Comment by xiaotuan** [comment]
具体哪个文件包重名，如果重名，你可以自行修改为不重名即可。

**Comment by xushaowen** [comment]
用幸运破解器装下去了，然后发现没有启动图标。

**Comment by honghongtu** [comment]
用幸运破解器安卓核心破解装下去了，然后发现没有启动图标。

**Comment by xiaotuan** [comment]
这个apk默认设置是通过暗码打开，且apk需要和系统源代码一起编译或者使用系统签名文件对其进行签名才可以使用的
